name: Feature/Hotfix CI
on:
  push:
    branches: [ "feature-keyboard","feature-power","feature-sqrt","hotfix" ]
  pull_request:
    branches: [ "feature-keyboard","feature-power","feature-sqrt","hotfix" ]
  workflow_dispatch:

jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - name: Super-Linter
        # You may pin to the exact commit or the version.
        # uses: super-linter/super-linter@a8150b40c89574adb5f68bf9502b890a236a06b3
        uses: super-linter/super-linter@v5.7.2
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Run a one-line script
        run: echo Hello, world!
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
